import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('UI shell imports extracted component modules', async () => {
  const shell = await import('../ui/shell.js')
  const appIcon = await import('../ui/components/app-icon.js')
  const apps = await import('../ui/components/apps.js')
  const browse = await import('../ui/components/browse.js')
  const catalogActions = await import('../ui/components/catalog-actions.js')
  const consentModals = await import('../ui/components/consent-modals.js')
  const deviceSync = await import('../ui/components/device-sync.js')
  const federatedSearch = await import('../ui/components/federated-search.js')
  const library = await import('../ui/components/library.js')
  const permissionEvidence = await import('../ui/components/permission-evidence.js')
  const searchResults = await import('../ui/components/search-results.js')
  const settings = await import('../ui/components/settings.js')
  const shipCheckReport = await import('../ui/components/ship-check-report.js')
  const sites = await import('../ui/components/sites.js')
  const trustWidgets = await import('../ui/components/trust-widgets.js')
  const catalogApps = await import('../ui/lib/catalog-apps.js')
  const permissions = await import('../ui/lib/permissions.js')
  const settingsLib = await import('../ui/lib/settings.js')
  assert.equal(typeof shell.App, 'function')
  assert.equal(typeof appIcon.AppIcon, 'function')
  assert.equal(appIcon.safeIconSrc('javascript:alert(1)'), null)
  assert.equal(typeof apps.Apps, 'function')
  assert.equal(typeof browse.Browse, 'function')
  assert.equal(typeof catalogActions.AddToCatalogButton, 'function')
  assert.equal(typeof catalogActions.useMyCatalogWriter, 'function')
  assert.equal(typeof catalogActions.catalogActionTargets, 'function')
  assert.deepEqual(catalogActions.catalogActionTargets({ id: 'demo', driveKey: 'abc', link: 'hyper://abc/' }), ['demo', 'abc', 'hyper://abc/'])
  assert.equal(typeof consentModals.LoginConsent, 'function')
  assert.equal(typeof consentModals.SwarmConsent, 'function')
  assert.equal(typeof consentModals.Onboarding, 'function')
  assert.equal(consentModals.SCOPE_LABELS['profile:name'].label, 'Display name')
  assert.equal(typeof deviceSync.DeviceSync, 'function')
  assert.equal(typeof federatedSearch.FederatedSearch, 'function')
  assert.equal(typeof library.Library, 'function')
  assert.equal(typeof permissionEvidence.usePermissionEvidence, 'function')
  assert.equal(typeof searchResults.SearchProvenanceBadges, 'function')
  assert.equal(typeof searchResults.SearchResultRow, 'function')
  assert.equal(typeof settings.Settings, 'function')
  assert.equal(typeof shipCheckReport.ShipCheckReport, 'function')
  assert.equal(typeof sites.Sites, 'function')
  assert.equal(typeof trustWidgets.AppTrustBadges, 'function')
  assert.equal(typeof trustWidgets.AppTrustDetail, 'function')
  assert.equal(typeof trustWidgets.CatalogSourceChips, 'function')
  assert.equal(typeof trustWidgets.SiteTrustBadges, 'function')
  assert.equal(catalogApps.catalogAppSearchText({ name: 'Demo', categories: ['Tools'] }), 'demo tools')
  assert.equal(catalogApps.dedupeApps([{ driveKey: 'a'.repeat(64), name: 'one' }, { driveKey: 'a'.repeat(64), name: 'two' }]).length, 1)
  assert.deepEqual(permissions.normalizeLoginGrant({ driveKeyHex: 'abc' }), { driveKeyHex: 'abc', driveKey: 'abc' })
  assert.deepEqual(settingsLib.unwrapSettings({ settings: { ok: true } }), { ok: true })
})

test('device sync reveal flow keeps pairing encryption keys out of status state', () => {
  const source = readFileSync(new URL('../ui/components/device-sync.js', import.meta.url), 'utf8')
  assert.match(source, /CMD_SYNC_GET_INVITE/)
  assert.match(source, /CMD_SYNC_COMPACT/)
  assert.match(source, /inviteRevealed/)
  assert.match(source, /hidden encryption key/)
  assert.match(source, /Sync log retention/)
  assert.match(source, /Compact sync log/)
  assert.doesNotMatch(source, /formatSyncInvite\(status\.key,\s*status\.encKey\)/)
  assert.doesNotMatch(source, /status\.encKey/)
})

test('backend sync status is redacted and invite fetch is explicit', () => {
  const source = readFileSync(new URL('../backend/index.js', import.meta.url), 'utf8')
  const statusStart = source.indexOf('rpc.handle(C.CMD_SYNC_STATUS')
  const inviteStart = source.indexOf('rpc.handle(C.CMD_SYNC_GET_INVITE', statusStart)
  assert.notEqual(statusStart, -1)
  assert.notEqual(inviteStart, -1)
  const statusBlock = source.slice(statusStart, inviteStart)
  assert.match(statusBlock, /inviteAvailable/)
  assert.match(statusBlock, /keyAudit/)
  assert.doesNotMatch(statusBlock, /encKey\s*:/)
  assert.match(source.slice(inviteStart, source.indexOf('// Enable + create', inviteStart)), /encKey\s*:/)
  assert.match(source, /CMD_SYNC_COMPACT/)
  assert.match(source, /sy\.compact\(\)/)
})

test('settings diagnostics include startup budget and deferral surfaces', () => {
  const source = readFileSync(new URL('../ui/components/settings.js', import.meta.url), 'utf8')
  assert.match(source, /StartupBudgetSection/)
  assert.match(source, /status\.bootBudget/)
  assert.match(source, /status\.startupDeferral/)
  assert.match(source, /Deferred surfaces/)
})

test('storage diagnostics expose low-priority sampling progress', () => {
  const backend = readFileSync(new URL('../backend/index.js', import.meta.url), 'utf8')
  const settings = readFileSync(new URL('../ui/components/settings.js', import.meta.url), 'utf8')
  const diagnostics = readFileSync(new URL('../ui/lib/performance-diagnostics.js', import.meta.url), 'utf8')
  assert.match(backend, /storageSampleProgress:\s*storageSample\.sampleProgress/)
  assert.match(backend, /scheduleStorageUsageSample\(\{\s*force:\s*true,\s*delayMs:\s*1500\s*\}\)/)
  assert.match(backend, /walkStorageUsage\(dir/)
  assert.match(settings, /storageSampleProgressLabel/)
  assert.match(diagnostics, /Low-priority scan/)
})

test('moderator queue keeps manifest previews and reject reasons wired', () => {
  const source = readFileSync(new URL('../ui/components/apps.js', import.meta.url), 'utf8')
  assert.match(source, /PendingManifestPreview/)
  assert.match(source, /rejectReasons/)
  assert.match(source, /payload\.reason/)
  assert.match(source, /payload\.manifest/)
  assert.match(source, /Reject reason/)
})

test('ship check report wires one-click fresh-peer verifier command', () => {
  const boot = readFileSync(new URL('../ui/boot.js', import.meta.url), 'utf8')
  const report = readFileSync(new URL('../ui/components/ship-check-report.js', import.meta.url), 'utf8')
  const apps = readFileSync(new URL('../ui/components/apps.js', import.meta.url), 'utf8')
  const sites = readFileSync(new URL('../ui/components/sites.js', import.meta.url), 'utf8')
  assert.match(boot, /CMD_RUN_FRESH_PEER_VERIFY:\s*217/)
  assert.match(report, /Run fresh-peer verifier/)
  assert.match(apps, /CMD_RUN_FRESH_PEER_VERIFY/)
  assert.match(sites, /CMD_RUN_FRESH_PEER_VERIFY/)
})
